### ISSUE TITLE
change order of steps

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/hs-crypto#1]
Following the instruction on getting started I encountered an issue in the order.

If you look at the part below 

----
3. **Leave imprint mode in the target domain**

  A domain in imprint mode is not considered secure. You cannot run most of the administrative commands, such as loading the new master key register, in imprint mode.

  * After you install one or more domain administrators, exit imprint mode by using the command:

I followed the instructions mentioned 
    ```
    ibmcloud tke domain-exit-impr
    ```
    {: pre}

    The command to exit imprint mode must be signed by one of the installed domain administrators.

  * To select the administrator to sign the command, use the command:

  **Tip**: The command to exit imprint mode must be signed by a domain administrator. After the domain leaves imprint mode, all commands to the domain must be signed.

    ```
    ibmcloud tke sigkey-sel
    ```
    {: pre}

    A list of signature key files found on the workstation is displayed.

    When prompted, enter the key number of the signature key file to select for signing subsequent administrative commands.
---

The steps indicate that you can leave the imprint mode without an additional step. What I faced was that it is needed, required to use 
```
ibmcloud tke sigkey-sel
```
first and then I can leave the imprint mode. I think the order should be changed or it should be better visible to first select a key and then leave imprint mode

**Comment by TiffanyLiIBM** [comment]
Hi @stschmitt Stefan,

Sorry for not getting back to you earlier. For unknown reasons, I was not notified of this issue. Are you saying that by following the steps in the current doc (https://cloud.ibm.com/docs/services/hs-crypto?topic=hs-crypto-initialize-hsm#initialize-hsm), you were unable to leave imprint mode? 
I suppose we should be able to exit imprint mode if we run `ibmcloud tke sigkey-sel` as described in step 1. You will only need to enter the signature key file password after you run `ibmcloud tke sigkey-sel`. 

Here is a demo video for your reference: https://www.youtube.com/watch?v=QAhr46qJBVo&feature=youtu.be. Please let me know if you still have any problems.

**Comment by TiffanyLiIBM** [comment]
Closing this issue as no further comments were received.
