### ISSUE TITLE
Prohibited term: master

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/hs-crypto#10]
* https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-introduce-service
* https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-management-utilities
* https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm

Replace "master" in "master key" with an approved alternative. Options: controller, primary, parent. 
@TiffanyLiIBM Please work with a technical SME for input on the proposed update. 

This term is included in our product glossary. We're working with IBM Terminology to update the term in the DB so we can then refresh the glossary.

**Comment by TiffanyLiIBM** [comment]
@cdmauney Thanks for the info. As "master key" is a term that is widely used in IBM, not sure whether there are any corporate-level suggestions already?

**Comment by cdmauney** [comment]
@TiffanyLiIBM I'm working with corporate on determining which alternative to use. I'll let you know as soon as we reach a decision.

**Comment by TiffanyLiIBM** [comment]
Hi @cdmauney,

I found that the term "master" is prohibited in the terminology DB while "master key" is still acceptable: http://tlwi.w3-969.ibm.com/standards/terminology/cgi-bin/lookup?ug=corporate&term=master+key&submit=Search&source=en&target_switch=none&template=simple&db_name=LOGOS&11=main+form&11=acronym%7Eabbreviation&11=prohibited

Does it mean that we can continue to use the term with no problem?

**Comment by cdmauney** [comment]
@TiffanyLiIBM Sorry for the delay. Per guidance from corporate, we're updating the term in the product glossary to "controller key." So if you can make a similar update in your content, we can then close this issue.

**Comment by TiffanyLiIBM** [comment]
Hi @cdmauney,

I just did a search in the Terminology DB and found "master key" is acceptable: http://tlwi.w3-969.ibm.com/standards/terminology/cgi-bin/lookup?ug=corporate&term=master+key&submit=Search&source=en&target_switch=none&template=simple&db_name=LOGOS&11=main+form&11=acronym%7Eabbreviation&11=prohibited

And also, according to the blog posted in w3publisher by Dale Davis Jones, "master" can be used as long as it is not paired with "slave": https://w3.ibm.com/w3publisher/academy-assets/blog/8d40a4a0-d026-11ea-b86d-6d77d417956c
_"Certain uses of the term "master" are acceptable when it is not paired with the term "slave". Context is key:
If the term master is used in a context such as "Master Data Management" where there is no "Slave Data Management" counterpart, then that use of the term master is acceptable and not offensive. 
Additional examples where the term master is acceptable, assuming it is not used in conjunction with a related term including the word slave: masterpiece, Scrum Master, Master Inventor"_

I really think we should be cautious about making that change. "Controller key" does not mean anything to a user who gets used to this term for years. Even if we need to make the change, there are some other alternatives that make better sense than "controller key", such as "root-wrapping key".

Please reconsider making the change. Thanks and let me know if further discussion is needed.

**Comment by cdmauney** [comment]
@TiffanyLiIBM Confirmed with corporate that no update is necessary, and the use of "master key" is acceptable. Closing.
