### ISSUE TITLE
Document  common possible cause for no visible crypto units on TKE setup

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/hs-crypto#12]
If the I work with multiple users it might happen that the owner of the crypto instance is not the one who setup the 
Root Key. 
In this case the Roles and Permissions are important. 
The error case shown is as following, but does not indicate that it could be a permission issue. 

```
ibmcloud tke cryptounits
API endpoint:     https://cloud.ibm.com
Region:           XX-XX
User:             foo.bar@domgain.email
Account:         myaccount (GUID)
Resource group:   Default

No service instances were found for the current resource group.
```

Please add this condition and the multiple cases why this could happen
-> wrong region, wrong account, missing roles

**Comment by TiffanyLiIBM** [comment]
@stschmitt Hi Stefan, 
I couldn't tell from the issue which topic it was opened against, but I guess you meant to add a new troubleshooting item. Please correct me if I was wrong.

@liuxjep June - Could you help handle this during your day time tomorrow? Thanks!

**Comment by liuxjep** [comment]
@TiffanyLiIBM Sure, Tiffany!
@stschmitt Hi Stefan, Thanks for the comments. We added an item in the troubleshooting topic describing this issue. Please check it out at: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-troubleshooting#troubleshoot-list-crypto-units
Could you take a look and let us know your comments? Thanks!

**Comment by TiffanyLiIBM** [comment]
@stschmitt Could you help take a look at the troubleshooting doc updated above? We'd like to close this issue if you don't have any comments to it and push the content to prod.

**Comment by stschmitt** [comment]
Thanks looks good to me
