### ISSUE TITLE
Typo on https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-get-started#manage-data-key

### ISSUE THREAD

**Issue by eshrak-assaf** [ibm-cloud-docs/hs-crypto#18]
Under: Importing your own keys > Description of Key type setting is: "The type of key that you would like to manage in Hyper Protect Crypto Services. You can seletct Root key or Standard key."

There is a typo: seletct. 
Please correct to be select.

**Comment by liuxjep** [comment]
@eshrak-assaf Thanks for spotting this. We have corrected it to be "select", please check it out at: https://cloud.ibm.com/docs/hs-crypto/index.html#manage-data-key
