### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by dlentz-ibm** [ibm-cloud-docs/hs-crypto#19]
There are two links on this page, each with the text  "virtual routing and forwarding (VRF) and service endpoints". The first occurrence of the link works but the second occurrence of the link sends you to a "Document not found" page.

**Comment by liuxjep** [comment]
@dlentz-ibm Thanks for spotting this. Do you mean on this page: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-provision? We have fixed the broken link, please check it out. Thanks.

**Comment by TiffanyLiIBM** [comment]
No more comment received. Closing...
