### ISSUE TITLE
KP CLI plugin should be documented in CLI docs

### ISSUE THREAD

**Issue by nathan-hekman** [ibm-cloud-docs/hs-crypto#20]
Currently, the only docs for the `kp` CLI plugin are here: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-set-up-cli

They should also be added to the IBM Cloud CLI reference: https://cloud.ibm.com/docs/cli?topic=analytics-engine-cli-plugin-CLI_analytics_engine

**Comment by cloudpitchford** [comment]
The canonic reference for KP CLI is: https://cloud.ibm.com/docs/key-protect?topic=key-protect-cli-reference

Several versions are supported and referenced in the collection. Collection managers can re-use topics per the documentation.

**Comment by TiffanyLiIBM** [comment]
@cloudpitchford Hi Chris, per the Cloud doc guidance, the service CLI doc should be part of the IBM Cloud CLI doc set. See: https://test.cloud.ibm.com/docs/writing?topic=writing-cli-cmd-ref for instructions.

**Comment by cloudpitchford** [comment]
Thanks for the guidance! I have an internal ticket set for that task. Please contact me via email or Slack for details, thanks!

**Comment by TiffanyLiIBM** [comment]
Since you are tracking it in another issue, I am going to close this one opened against HPCS. Thanks!
