### ISSUE TITLE
HPCS Integrated service list is not up2date

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/hs-crypto#21]
The list of services for HP Crypto which are interated with this service are not up2date
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-integrate-services

services like ICD and others are missing which leads to customer confusion
https://cloud.ibm.com/docs/databases-for-postgresql?topic=cloud-databases-hpcs

**Comment by TiffanyLiIBM** [comment]
The doc has been updated with the latest integration info: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-integrate-services
Please find detailed effort tracked at: https://github.ibm.com/ZaaS/zcrypto-backlog/issues/3316
