### ISSUE TITLE
text indicates destroyed keys can't be recovered, table differs

### ISSUE THREAD

**Issue by crdotson** [ibm-cloud-docs/hs-crypto#22]
The text says that destroyed keys cannot be recovered, but the table shows "recovery" as a valid action against destroyed keys.

**Comment by liuxjep** [comment]
@crdotson Hi Chris. Thanks for the feedback. From my side, I can't see which page you are referring to. Could you specify the page that you are talking about? We can then make updates accordingly. Thanks!

**Comment by liuxjep** [comment]
@crdotson Hi Chris, we have refreshed our docs for a few times. Not sure whether the problem you mentioned has been fixed or not. Could you please check? Then we can close this issue. Thanks!

**Comment by TiffanyLiIBM** [comment]
No more comments received. Closing...
