### ISSUE TITLE
Clarify HPCS AWS & Azure support.

### ISSUE THREAD

**Issue by mark-buckwell** [ibm-cloud-docs/hs-crypto#24]
Currently this question in the Q&A implies an AWS cloud service such as S3 Storage could use HPCS.

**Can I use Hyper Protect Crypto Services along with other cloud provider services such as AWS and Azure?**
Yes. Any application can connect to Hyper Protect Crypto Services and use our APIs from anywhere on the internet.

I suggest replacing the Q&A with:

**Can I use Hyper Protect Crypto Services for applications hosted in other cloud service providers such as AWS, Azure and GCP?**
Yes, An application hosted in other cloud service providers could call the public APIs for BYOK or PKCS#11 with an appropriate network connection.

**Comment by liuxjep** [comment]
@mark-buckwell Thanks for the feedback. I have updated the page per your suggestion, please check it out at: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-faq-provisioning-operations#faq-hpcs-other-cloud-vendor. As HPCS provides the KYOK feature, I changed BYOK to KYOK. If you have any further comments, please let me know. Thanks.

**Comment by liuxjep** [comment]
No further comments were received. Closing this issue...
