### ISSUE TITLE
Hyper Crypto Protect Documentation missing section Cloud Image Templates

### ISSUE THREAD

**Issue by verdecal** [ibm-cloud-docs/hs-crypto#25]
There is integration between KeyProtect and IMAGE TEMPLATE:
https://cloud.ibm.com/docs/key-protect?topic=key-protect-integrate-services&interface=ui#compute-integrations

In the IMPORT CUSTOM IMAGE there are 3 choices for encryption: Provider managed, KP and HPCS.

 

In the HPCS page in section Compute service integrations there is a missing table entry IBM Cloud Image Templates

https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-integrate-services

**Comment by TiffanyLiIBM** [comment]
@verdecal Thank you for providing the feedback! We've made updates to the HPCS doc accordingly. Please see: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-integrate-services#compute-integration.

If you have any other comments, please let us know. Thanks!

**Comment by TiffanyLiIBM** [comment]
No more comments received. Closing...
