### ISSUE TITLE
Clarify in more detail how the HPCS instance ID drop down works

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#28]
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-tutorial-kmip-vmware#tutorial-vmware-configure

4.) Select the Initialize service instance option and Hyper Protect as the key management type.
- Select the Hyper Protect Crypto Services instance ID that stores your root key and key encryption key. You can click the Retrieve button to get a list of Hyper Protect Crypto Services instances under your IBM Cloud account.
**Add a note like:** "(Only IDs of Hyper Protect Crypto Services instances that contain at least one root key will be displayed in this list.)"

Reason: If a HPCS instance exists, but a root key is not yet created in this instance, the instance id will not be listed in the drop down, which may be counter-intuitive.

**Comment by TiffanyLiIBM** [comment]
@Timo-1 Thanks much for your feedback!
Please see the updated doc at: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-tutorial-kmip-vmware#tutorial-vmware-configure.

We've already included creating root keys as a prerequisite in the tutorial. And I agree with you.  A note in this specific step will make it more clear what service instances are to be retrieved.

**Comment by Timo-1** [comment]
@TiffanyLiIBM Thank you - the updated doc looks good !

**Comment by TiffanyLiIBM** [comment]
Pushed to Prod. Closing...
