### ISSUE TITLE
Update and enhance page Setting up PKCS #11 API user types

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#29]
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access#1-assign-the-custom-roles-to-the-so-user-service-id
and
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access#2-assign-the-custom-roles-to-the-normal-user-service-id

The following seems outdated and a bit confusing:
(5) "Click No service access under What type of access do you want to assign? and select Hyper Protect Crypto Services."

Proposed change:
(5) Under Which service do you want to assign access to? select Hyper Protect Crypto Services.

----

Between (5) and (6) there is one step missing:
Proposed addition:
(5.1) Under How do you want to scope the access? select Resources based on selected attributes

**Comment by TiffanyLiIBM** [comment]
@Timo-1 Hi Timo,
Thanks much for your comments! Could you take a look at the updated doc and let me know if you have additional comments?

https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access#1-assign-the-custom-roles-to-the-so-user-service-id

**Comment by Timo-1** [comment]
@TiffanyLiIBM Thank you - this looks good.
