### ISSUE TITLE
"Type of key" and "Envelope encryption" links

### ISSUE THREAD

**Issue by William-Scott-Holmes** [ibm-cloud-docs/hs-crypto#3]
...are linking to Key Protect content.

**Comment by TiffanyLiIBM** [comment]
@William-Scott-Holmes Thanks for your comments. We are in the middle of creating a envelope encryption topic for Crypto, and will update the links when it is done.

**Comment by TiffanyLiIBM** [comment]
The new envelope encryption topic has been created: https://cloud.ibm.com/docs/services/hs-crypto?topic=hs-crypto-envelope-encryption.

Closing this issue...
