### ISSUE TITLE
Another update on page Setting up PKCS #11 API user types

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#30]
Under  https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access#create-key-operator
add the following action to the list under (7):

`hs-crypto.discovery.listservers`

------

In addition, on the same page, it seems the UI and the Docu do not match 100%:
Proposed change 

Old:
(4) Click Assign service ID additional access, and then click the IAM services button.

New / proposed update:
(4) Click Assign access to the service ID, and then click the IAM services button.

here:

https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access#1-assign-the-custom-roles-to-the-so-user-service-id
and 
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access#2-assign-the-custom-roles-to-the-normal-user-service-id
and 
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access#3-assign-the-custom-roles-to-the-anonymous-user-service-id

**Comment by Timo-1** [comment]
Hi @TiffanyLiIBM , could you have a look at this issue ?
Thank you!
Timo

**Comment by Hestia-Zhang** [comment]
Made updates accordingly. Thank you @Timo-1 ! https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-best-practice-pkcs11-access

**Comment by Timo-1** [comment]
Thank you @Hestia-Zhang - looks good !

**Comment by TiffanyLiIBM** [comment]
Pushed to Prod. Closing...
