### ISSUE TITLE
Clarify the instructions for ordering smart card readers

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#32]
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-prepare-management-utilities#ordering-smart-card-readers

Current text:
The supported smart card reader type is SPR332 v2.0 Secure Class 2 PIN Pad Reader (part number 905127-1). The following are a few third-party online shops where you can order a smart card reader. The deliver policy might vary depending on your geographical locations:

Proposed change:
You need two smart card readers of type Identiv SPR332 v2.0 Secure Class 2 PIN Pad Reader (part number 905127-1). You can order the smart card readers from third-party online shops. For illustration there is a list of example links to various online shops below:

**Comment by TiffanyLiIBM** [comment]
Hi @Timo-1,

Thanks much for the proposal! I've already made updates accordingly with some tweaks. Please se: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-prepare-management-utilities#ordering-smart-card-readers.
 
As to the third-party shop list, I still need Lane's help to get the updates done. Please see: https://github.ibm.com/ZaaS/zcrypto-backlog/issues/5366#issuecomment-42703815.

**Comment by Timo-1** [comment]
Thank you @TiffanyLiIBM -it's better to understand now, in particular the fact that the list of online shops is just an example and is not exhaustive.

**Comment by TiffanyLiIBM** [comment]
Hi @Timo-1,
I have updated the introductory sentence to the following. Please let me know if you have additional comments. Thanks!

```
You need to order two smart card readers `Identiv SPR332 v2.0 Secure Class 2 PIN Pad Reader` (part number 905127-1), from third-party online shops. The following list contains a few example online shopping sites where the required smart card readers are available. The deliver policy might vary depending on your geographical locations:
```

**Comment by TiffanyLiIBM** [comment]
No more comments received. Closing...
