### ISSUE TITLE
The need for the directory to be created/pre-exist should be made explicit 

### ISSUE THREAD

**Issue by hancockp-at-ibm** [ibm-cloud-docs/hs-crypto#34]
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-prerequisite

point (3) says to set the variable CLOUDTKEFILES to a directory name. It should be made clear to the reader that the directory must exist before they run any TKE commands.

**Comment by liuxjep** [comment]
@hancockp-at-ibm Hi, thanks for the comments. I updated the point (3) to be:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/46957998/167994583-da7e1849-f29d-4ee7-8d95-3aa83ab4ea84.png">
Please check it at: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-prerequisite and let me know if you have any further comments. Thanks!

**Comment by hancockp-at-ibm** [comment]
Al looks good. Thank you.

[signature_470849034]

From: liuxjep ***@***.***>
Date: Thursday, 12 May 2022 at 05:54
To: ibm-cloud-docs/hs-crypto ***@***.***>
Cc: Peter Hancock1 ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/hs-crypto] The need for the directory to be created/pre-exist should be made explicit (Issue #34)
@hancockp-at-ibm Hi, thanks for the comments. I updated the point (3) to be: Please check at: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-prerequisite and let me know if you have any further comments. Thanks! --
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd
@hancockp-at-ibm Hi, thanks for the comments. I updated the point (3) to be: [image] Please check at: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-prerequisite and let me know if you have any further comments. Thanks! -- Reply to this email directly or view it on GitHub: https://github.com/ibm-cloud-docs/hs-crypto/issues/34#issuecomment-1124528154<https://github.com/ibm-cloud-docs/hs-crypto/issues/34#issuecomment-1124528154> You are receiving this because you were mentioned. Message ID:

Unless otherwise stated above:

IBM United Kingdom Limited
Registered in England and Wales with number 741598
Registered office: PO Box 41, North Harbour, Portsmouth, Hants. PO6 3AU

**Comment by liuxjep** [comment]
@hancockp-at-ibm Thanks. Closing this issue...
