### ISSUE TITLE
Need to add a Smart-Card Calculator

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#35]
The smart-card requirements documents linked to at https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-tke-procedures will need to be supported by a `Calculator` that will help determine how many "Smart Card Readers" and "Smart Cards" are required.

Timo Kussmaul from our team has developed a simple calculator, which needs to be added to the documentation: https://ibm.ent.box.com/file/984688389180

**Comment by TiffanyLiIBM** [comment]
Hi @sandeep-at-ibm,

Could you advise whether the calculator info (https://ibm.ent.box.com/file/984688389180) is ready to be added to the doc? Are you suggesting we add the info to the TKE procedure paper (https://cloud.ibm.com/media/docs/downloads/hs-crypto/IBMCloud_HyperProtectCryptoSevices_TKEProcedures.pdf), or the online documentation?

**Comment by sandeep-at-ibm** [comment]
Hi @TiffanyLiIBM 
yes, the calculator is ready to go as far I know

@timo ??

**Comment by Timo-1** [comment]
@TiffanyLiIBM @sandeep-at-ibm 

The calculator fits here:

- https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-prepare-management-utilities#order-smart-card

and/or here 

- https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-faq-provisioning-operations#faq-smart-card-setup

(I don't think it fits in the TKE Procedures guide, though).
Both sections touch on the number of required smart cards. The second section is linked from the first section, but the link itself is not really explained very clearly ("[create backup copies of all used smart cards](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-faq-provisioning-operations#faq-smart-card-setup)").  Maybe these sections can be consolidated and the link be explaiend more clearly.

I have refined the Powerpoint, and it is ready to be added to the doc. Please review and rephrase as appropriate.

**Comment by TiffanyLiIBM** [comment]
Thanks @Timo-1 @sandeep-at-ibm.
I have just opened another issue in the backlog repo to track the further doc work. Will send you a copy for review when the draft is ready.
https://github.ibm.com/ZaaS/zcrypto-backlog/issues/6134
