### ISSUE TITLE
Typo in email address on page hs-crypto-prepare-management-utilities

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#37]
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-prepare-management-utilities

Step 1 -> (2) -> There is a typo in the email address "zcat@ibm.com@ibm.com "

**Comment by TiffanyLiIBM** [comment]
@Timo-1 Hi Timo,

Thanks for spotting this and letting us know. The typo has been fixed. See: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-prepare-management-utilities.
