### ISSUE TITLE
Update doc to add Permissions required for HPCS operations

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#39]
The Doc at https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-manage-access needs more details on the `minimum` access requirements for various HPCS operations like:

- View the HPCS UI Dashboard on cloud.ibm.com
- Create Keys
- Rotate Keys
- Delete Keys

with the granular roles that have been added to IAM:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/61752731/196197913-37611aab-0379-456c-9fab-aea56e17132f.png">

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm - You were referring to the standard plan doc. Please check out the check for UKO instead: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-uko-manage-access&interface=ui#uko-service-access-roles. 
The details are in the table shown below. Please let me know whether it solves your problem. Thanks!
<img width="815" alt="image" src="https://user-images.githubusercontent.com/40377681/196324090-9a931cbb-a804-4bb6-82cd-c1dda7eb4ee6.png">

**Comment by sandeep-at-ibm** [comment]
@TiffanyLiIBM 
The Power Team and the CISO/SOS groups will be using a Standard instance. 
I think, we need the document - new one if that is going to be the one living - to address the permissions for the Standard instance too.

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm 
If it is for the standard plan only, we do have the info in the doc that you referred to: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-manage-access&interface=ui#service-access-roles.

There are multiple tabs on the table. You can click the ellipsis on the right to switch between tabs.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/40377681/196328655-b911fa55-9a36-4aba-a027-58a769183e6e.png">

However, I am confused to see these three roles listed under the standard plan though. They should be specific to the UKO plan:
Vault administrator
Key custodian - Creator
Key custodian - Deployer

@marco - thoughts?

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm Please let me know whether there are any actions we need to take for this issue. Thanks!

**Comment by sandeep-at-ibm** [comment]
@TiffanyLiIBM for now I think we are good. Will reopen the issue if required
