### ISSUE TITLE
Depiction of KeyStores in Fig2 needs an update

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#40]
- Fig.2 suggests that you will need “separate” HPCS instances for each Application. 
- It should be modified to indicate that each Application can have it’s own KeyStore under the same HPCS instance

**Comment by sandeep-at-ibm** [comment]
@TiffanyLiIBM do you have the source for Fig 2 on this page?

https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-architecture-workload-isolation

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm Thanks for the comment. I've sent the source file to you through slack. Please check out.

@liuxjep Could you help make the changes to the diagram accordingly? Thanks!

**Comment by liuxjep** [comment]
@sandeep-at-ibm Hi Sandeep, the diagram has been updated on test, please check it out at: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-architecture-workload-isolation#workload-isolation
Please let me know if you have any further comments. Thank you!

**Comment by sandeep-at-ibm** [comment]
@TiffanyLiIBM as mentioned on Slack, I do not have access to "Adobe Illustrator". Here is my view of how the picture should look like:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/61752731/199491068-da8c67f4-d5c2-46f7-bc7f-94da5355b021.png">

**Comment by sandeep-at-ibm** [comment]
Thanks @liuxjep 
Appreciate the quick turn around. It will help with our messaging to Johnson Controls
