### ISSUE TITLE
Add recommendation to setup Acitivity Tracker for HPCS

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#41]
Add a strong and easy to read recommendation - on this page https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-provision&interface=ui - to enable IBM Cloud Activity Tracker for the Hyper Protect Crypto Services instance.

See following sentence here: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-at-events
"To enable IBM Cloud Activity Tracker for your Hyper Protect Crypto Services instance, you need to provision an instance of the IBM Cloud Activity Tracker service in the same region where your Hyper Protect Crypto Services instance is located."

Goal: Avoid that customer does a key ceremony which is not audited in his AT.

**Comment by TiffanyLiIBM** [comment]
@Timo-1 Thanks for the comment.
I've updated to [the doc](https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-provision&interface=ui#provision-next) to include the AT tracker provisioning as a next step. Please let me know whether it is sufficient:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/40377681/202345874-96bca4aa-3829-4053-b3be-68ad8747fc6b.png">

**Comment by TiffanyLiIBM** [comment]
@Timo-1 I would like to close this issue if there is no more comments. Thanks!

**Comment by Timo-1** [comment]
Thank you @TiffanyLiIBM.
Can you emphasize the recommendation to setup AT in a stronger way ?

The current paragraph is very neutral.

E.g. add a a sentence which illustrates the advantages of AT like :

As a security officer, auditor, or manager, you can use the IBM Cloud® Activity Tracker service to monitor the status of your instance and how administrators, users and applications interact with IBM Cloud® Hyper Protect Crypto Services. To enable IBM Cloud Acitivty Tracker for your ...

**Comment by TiffanyLiIBM** [comment]
Hi @Timo-1,
Many thanks for the suggestion. I've adjusted the doc accordingly:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/40377681/204203923-2c7f636d-6d4d-4051-bbfd-548e38eb3808.png">

**Comment by Timo-1** [comment]
Thanks @TiffanyLiIBM . Looks good !

**Comment by TiffanyLiIBM** [comment]
Change pushed to Prod. Closing...
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-provision&interface=ui
