### ISSUE TITLE
Links in document need to be updated

### ISSUE THREAD

**Issue by seenusuvarna** [ibm-cloud-docs/hs-crypto#42]
There are several links in https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-integrate-services#database-integration
section for integration that link to nowhere.  That needs to be updated correctly so that integration can be done correctly.

**Comment by liuxjep** [comment]
@seenusuvarna Thanks for spotting this. We have updated them accordingly.

**Comment by TiffanyLiIBM** [comment]
No more comments received. Closing...
