### ISSUE TITLE
page design broken

### ISSUE THREAD

**Issue by carstenmichel** [ibm-cloud-docs/hs-crypto#45]
Hello HPCS docu team,
there is an error in the page at https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm
in step 2:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/17781346/230312298-61fd164b-8072-497a-8645-576c2304868b.png">

**Comment by carstenmichel** [comment]
looks like 2 different parts of the page are overlaying each other

**Comment by TiffanyLiIBM** [comment]
Hello @carstenmichel,

Many thanks for bring this problem to our attention!
It has been resolved. Please view the latest doc at: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm.

Thanks again!
