### ISSUE TITLE
Clarify HPCS instance type for KMIP

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#46]
Please clarify in "Before you begin" section to provision a `Standard Instance` of HPCS.

Customer provisioned a UKO instance as that is the first option on the provisioning panel on IBM Cloud and tried to go through the KMIP provisioning process and went through multiple trouble shooting discussions, before it came to me. 

For KMIP / VMware services, a Standard Instance is required.

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm Thanks for the comment. Please find the updated topic at: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-tutorial-kmip-vmware. I will push the content out to Prod. in the next build of this week.

**Comment by sandeep-at-ibm** [comment]
Thanks @TiffanyLiIBM 
It'll be great if you can highlight the "Standard Plan" part of the bullet

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm We are not allowed to add highlighting just for emphasis in docs. However, I have made some more changes to the title and the overall flow. Hope it makes "standard plan" stand out.

<img width="923" alt="image" src="https://github.com/ibm-cloud-docs/hs-crypto/assets/40377681/5d289034-6ba5-45af-a45f-6fbdacdab5b7">
<img width="1005" alt="image" src="https://github.com/ibm-cloud-docs/hs-crypto/assets/40377681/a8aa9d65-e880-421a-9f4f-f3d92b6eda33">

**Comment by sandeep-at-ibm** [comment]
this looks good @TiffanyLiIBM 
thx
