### ISSUE TITLE
Update this doc to include TKE and SmartCard Documents

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#47]
This issue is to update this doc: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-tke-procedures

Current document-link https://cloud.ibm.com/media/docs/downloads/hs-crypto/IBM_Cloud_HyperProtectCryptoSevices_TKE_Procedures.pdf contains only the smart-card procedure.

- For TKE Key-part file procedure, please use this doc: https://github.ibm.com/ZaaS/zcat-assets/blob/main/docs/HPCS%20Key%20Ceremony%20Document%20-%20v0.1.docx
- For TKE Smart-Card procedure, @timo will update / refresh the [existing document](https://cloud.ibm.com/media/docs/downloads/hs-crypto/IBM_Cloud_HyperProtectCryptoSevices_TKE_Procedures.pdf) to reflect experiences gained from client engagements.

@TiffanyLiIBM pls share the DOC version of the existing PDF doc on this page, if you have access to it

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm @timo
You can find the the Word doc for the TKE smart card procedure at: https://ibm.ent.box.com/file/1147782684388. Please make sure to enable "Track changes" when you make any updates to the doc.
@sandeep-at-ibm Could you let me know whether the [key part file procedure](https://github.ibm.com/ZaaS/zcat-assets/blob/main/docs/HPCS%20Key%20Ceremony%20Document%20-%20v0.1.docx) is finalized? I can do an editorial review before getting it published. Please let me know. Thanks!

**Comment by sandeep-at-ibm** [comment]
@TiffanyLiIBM here is the latest version of the key-part-file procedure:
https://github.ibm.com/ZaaS/zcat-assets/blob/main/docs/HPCS%20Key%20Ceremony%20Document%20-%20v0.2.docx

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm I've completed the editorial review for the TKE CLI procedure doc: https://ibm.ent.box.com/file/1248130780986. Please take a look and let me know if it looks good. Thanks!

**Comment by sandeep-at-ibm** [comment]
@TiffanyLiIBM thanks for the review
@Timo-1 pls take a look when you get a chance

**Comment by Timo-1** [comment]
Thank you @TiffanyLiIBM Your edits in the TKE CLI procedure doc look good. @sandeep-at-ibm

**Comment by TiffanyLiIBM** [comment]
@Timo-1 Please let me know when the edits are done for the smart card procedure, so that I can request to re-upload both PDFs together. :)

**Comment by sandeep-at-ibm** [comment]
Thanks @Timo-1 & @TiffanyLiIBM 

we are good to publish
