### ISSUE TITLE
Incorrect statement about availability of recovery crypto units

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#49]
https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-recovery-crypto-unit

This sentence is not correct anymore:
"Currently, only the us-south and us-east regions are enabled with the recovery crypto units, which means, when a service instance is provisioned in either regions, you are by default enabled with the option to back up your master keys in the recovery crypto units located in both regions."

Recovery crypto units are no longer limited to us-south and us-east (I do not know if they are available gobally now or still limited to certain regions, but they are available at least in syd and tok, too).

**Comment by TiffanyLiIBM** [comment]
Hi Timo. Many thanks for the comment!!
@marco - Could you let us know what regions now support recovery crypto units, so that we can update the doc accordingly? Thanks!

**Comment by Timo-1** [comment]
created a new issue for the same defect --> https://github.com/ibm-cloud-docs/hs-crypto/issues/56

**Comment by TiffanyLiIBM** [comment]
Move to internal GH board:
https://github.ibm.com/ZaaS/zcrypto-backlog/issues/9799
