### ISSUE TITLE
Link to the documentation for initializing instance is missing

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/hs-crypto#5]
After you create a service instance you are provided the following error message with no indication or link to documentation on what to do: 

![image](https://user-images.githubusercontent.com/11874942/74668039-66bceb00-5172-11ea-8b8d-cdebed26ea4d.png)

Please add a link to steps to follow to complete the configuration.

**Comment by embrown-ibm** [comment]
@dpropser It appears that you are using an older instance of HPCS.  The **Learn more** link is a direct hyperlink to a topic in the documentation related to the error which provides help for the user on how to resolve the situation.  We have worked on this and the scenario you show above will look more similar to the following...

![image](https://user-images.githubusercontent.com/25669267/76951128-8e25e580-68e1-11ea-9024-e343c25ca1db.png)

![image](https://user-images.githubusercontent.com/25669267/76950372-4a7eac00-68e0-11ea-8216-b0f507f48787.png)

**Comment by dprosper** [comment]
Is this is different based on when my instance was created? i.e. this updated UI is not reflected on existing instances? 

![image](https://user-images.githubusercontent.com/11874942/76956050-aa2d8500-68e9-11ea-8fc0-141433e622b1.png)

**Comment by embrown-ibm** [comment]
@dprosper It depends.  It looks like you may have a production level of the UI.  When you bring up your UI, does the URL contain `test.cloud.ibm.com`?  If so, then you just need to update/repair your current instance.

**Comment by dprosper** [comment]
no, I am using cloud.ibm.com

**Comment by embrown-ibm** [comment]
@dprosper Are using the production level of the product.  You will not see changes until we make the new release available.  This should happen within the next 2 weeks.

**Comment by TiffanyLiIBM** [comment]
Closing this issue as the new implementation will fix the issue reported.
