### ISSUE TITLE
Since the deprecation of HPS DBaaS links should be updated

### ISSUE THREAD

**Issue by seenusuvarna** [ibm-cloud-docs/hs-crypto#50]
Some of the links to how to integrate HPCS with the service are not working, but the bigger concern is that integration for MongoDB still points to HP DBaaS MongoDB and states that it is deprecated.  Shouldn't the links point to the non-deprecated information as is suggested in the text on each page.  Otherwise the Alternative should be highlighted even more instead of just putting it in a colored box.  Need to draw attention to it.

https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-integrate-services

This is the page that needs to be updated on the previous link and avoid going to the depreciated page:
https://cloud.ibm.com/docs/hyper-protect-dbaas-for-mongodb?topic=hyper-protect-dbaas-for-mongodb-hpcs-byok

**Comment by TiffanyLiIBM** [comment]
Hi @seenusuvarna - Many thanks for the comment! We will investigate into the issue and make updates accordingly.

**Comment by dixu1214** [comment]
Hi @seenusuvarna, we have updated the documentation accordingly. Since HP DBaaS is deprecated, we removed the links in the Hyper Protect Crypto Service documentation. Besides, we have also fixed some broken links. 
Please feel free to let us know if you have any concerns or questions. 
Many thanks!
