### ISSUE TITLE
Add "storage-device" integration with HPCS

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#54]
We are now able to integrate HPCS with storage devices. This is going to be useful for the "Stratos" projects under the "Enterprise Data Architecture as a Service" effort.

I think we should update[ this document](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-integrate-services) with an introduction to "storage device integration" and a pointer to the detailed documentation here: https://developer.ibm.com/tutorials/awb-protect-storage-systems-with-ibm-hpcs-and-gklm/

@TiffanyLiIBM

**Comment by sandeep-at-ibm** [comment]
Add other integration topics as well:
- Hashicorp
- GaraSign
- KeyFactor

**Comment by TiffanyLiIBM** [comment]
Closing this issue. Tracking following effort at https://github.ibm.com/ZaaS/zcrypto-backlog/issues/9793
