### ISSUE TITLE
Key Rotation guidance update

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#55]
Hi, we have had several questions on key-rotation with VMware and other services that HPCS integrates with.
ZCAT has tested and documented various scenarios and this needs to be updated into the official documentation as well.

Please use [this Box-note](https://ibm.ent.box.com/notes/1428856127562) to create a single document for all key-rotation use cases.

Reach out if you have any questions

**Comment by TiffanyLiIBM** [comment]
Closing this issue and will track in internal channels.
