### ISSUE TITLE
Review note on availability of recovery crypto units

### ISSUE THREAD

**Issue by Timo-1** [ibm-cloud-docs/hs-crypto#56]
Review the following note
`Currently, only the us-south and us-east regions support recovery crypto units. Only service instances in these regions can use this command. For more information about supported regions, see [Regions and locations](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-regions).
`

This note is contained in multiple HPCS documentation pages, e.g. https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-recovery-crypto-unit and https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-recover-master-key-recovery-crypto-unit

But today recovery units can be created for HPCS instances in other locations apparently, at least if one uses Terraform.

Please work with Heidi and the HPCS development team to review and - if required - update this note.

There is also a similar note in the Terraform provider registry https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/hpcs which also needs to be reviewed.

**Comment by Timo-1** [comment]
please see this issue https://github.com/ibm-cloud-docs/hs-crypto/issues/49

**Comment by TiffanyLiIBM** [comment]
Move to internal GH board:
https://github.ibm.com/ZaaS/zcrypto-backlog/issues/9799
