### ISSUE TITLE
Production API docs python example has incorrect syntax

### ISSUE THREAD

**Issue by fritzheidi** [ibm-cloud-docs/hs-crypto#7]
The keyword `False` is capitalized in python.  In the documentation it is lowercase.

`"extractable": false` -> `"extractable": False`

Here is the link to the API docs where it should be updated.
https://cloud.ibm.com/apidocs/hs-crypto?code=python#create-a-new-key

**Comment by liuxjep** [comment]
@fritzheidi Hi Heidi, thanks for spotting this. The production docs has been updated accordingly. Please check it out at: https://cloud.ibm.com/apidocs/hs-crypto?code=python#create-a-new-key
Any further comments, please let us know. Thank you!

**Comment by fritzheidi** [comment]
@liuxjep Looks perfect, thank you!
