### ISSUE TITLE
Staging API docs do not match production API docs

### ISSUE THREAD

**Issue by fritzheidi** [ibm-cloud-docs/hs-crypto#8]
The staging python example is incorrect and causes an error when followed exactly.  The production docs are mostly correct except for the `False` keyword not being capitalized.  Could we change the staging python example to be like the production example?

staging -> https://test.cloud.ibm.com/apidocs/hs-crypto?code=python#create-a-key
production -> https://cloud.ibm.com/apidocs/hs-crypto?code=python#create-a-new-key

**Comment by liuxjep** [comment]
@fritzheidi Hi Heidi, thanks for spotting this. Apart from the `Create a key` method, I also found the following APIs which may have this similar problem. I updated them as well, could you help to verify whether they are correct? Thank you!

- `Create a key` - https://test.cloud.ibm.com/apidocs/hs-crypto?code=python#create-a-key
- `Invoke an action on a key` - https://test.cloud.ibm.com/apidocs/hs-crypto?code=python#invoke-an-action-on-a-key
- `Set key policies` - https://test.cloud.ibm.com/apidocs/hs-crypto?code=python#set-key-policies
- `Create an import token` - https://test.cloud.ibm.com/apidocs/hs-crypto?code=python#create-an-import-token

**Comment by fritzheidi** [comment]
@liuxjep Thank you, June! The updates look good 👍
